### ISSUE TITLE
OcropyResegment: ValueError: A LinearRing must have at least 3 coordinate tuples

### ISSUE THREAD

**Issue by jbarth-ubhd** [cisocrgroup/ocrd_cis#79] opened 2020-11-04 11:54 UTC
Log:
```
12:34:29.920 INFO processor.OcropyResegment - INPUT FILE 0 / P_00001
12:34:30.312 INFO processor.OcropyResegment - Page "OCR-D-N11_00001" uses 300.000000 DPI
12:34:30.321 WARNING processor.OcropyResegment - Page "OCR-D-N11_00001" region "region0000" contains only one line
...
12:34:39.847 WARNING ocrd_utils.crop_image - crop coordinates ((-1, 47, 1090, 97)) exceed image (1090x188)
12:34:39.881 WARNING processor.OcropyResegment - Largest label (2) largest contour (0) is small (0/53946) in line 
"region0004_li
ne0001"
Traceback (most recent call last):
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/bin/ocrd-cis-ocropy-resegment", line 8, in <module>
    sys.exit(ocrd_cis_ocropy_resegment())
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/lib/python3.7/site-packages/ocrd_cis/ocropy/cli.py", line 38, in 
ocrd_cis_o
cropy_resegment
    return ocrd_cli_wrap_processor(OcropyResegment, *args, **kwargs)
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/lib/python3.7/site-packages/ocrd/decorators/__init__.py", line 81, 
in ocrd_
cli_wrap_processor
    run_processor(processorClass, ocrd_tool, mets, workspace=workspace, **kwargs)
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/lib/python3.7/site-packages/ocrd/processor/helpers.py", line 69, 
in run_pro
cessor
    processor.process()
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/lib/python3.7/site-packages/ocrd_cis/ocropy/resegment.py", line 
234, in process
    extend_margins=margin, threshold_relative=threshold)
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/lib/python3.7/site-packages/ocrd_cis/ocropy/resegment.py", line 
107, in resegment
    polygon = Polygon(polygon).simplify(2).exterior.coords[:-1] # keep open
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/lib/python3.7/site-packages/shapely/geometry/polygon.py", line 
243, in __init__
    ret = geos_polygon_from_py(shell, holes)
  File "/beegfs/home/hd/hd_hd/hd_wu120/ocrd_all/venv/lib/python3.7/site-packages/shapely/geometry/polygon.py", line 
509, in geos_polygon_from_py
    ret = geos_linearring_from_py(shell)
  File "shapely/speedups/_speedups.pyx", line 252, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples
```

Workflow:
```
#!/bin/bash
#SBATCH --partition=single
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --mem=20gb
cd /beegfs/work/ws/hd_wu120-ubhd-ocrd-0/dobbert1861/14.tif >ocrd.log 2>&1 # ocrd.log neu schreiben
. $HOME/.bashrc >>ocrd.log 2>&1
. $HOME/ocrd_all/venv/bin/activate >>ocrd.log 2>&1
/usr/bin/time ocrd-create-mets.xml >>ocrd.log 2>&1
/usr/bin/time ocrd-olena-binarize -I OCR-D-IMG -O OCR-D-N1 -P impl wolf >>ocrd.log 2>&1
/usr/bin/time ocrd-anybaseocr-crop -I OCR-D-N1 -O OCR-D-N2 >>ocrd.log 2>&1
/usr/bin/time ocrd-olena-binarize -I OCR-D-N2 -O OCR-D-N3 -P impl wolf >>ocrd.log 2>&1
/usr/bin/time ocrd-cis-ocropy-denoise -I OCR-D-N3 -O OCR-D-N4 -P level-of-operation page >>ocrd.log 2>&1
/usr/bin/time ocrd-cis-ocropy-deskew -I OCR-D-N4 -O OCR-D-N5 -P level-of-operation page >>ocrd.log 2>&1
/usr/bin/time ocrd-tesserocr-segment-region -I OCR-D-N5 -O OCR-D-N6 >>ocrd.log 2>&1
/usr/bin/time ocrd-segment-repair -I OCR-D-N6 -O OCR-D-N7 -P plausibilize true >>ocrd.log 2>&1
/usr/bin/time ocrd-cis-ocropy-clip -I OCR-D-N7 -O OCR-D-N8 -P level-of-operation region >>ocrd.log 2>&1
/usr/bin/time ocrd-cis-ocropy-deskew -I OCR-D-N8 -O OCR-D-N9 -P level-of-operation region >>ocrd.log 2>&1
/usr/bin/time ocrd-tesserocr-segment-line -I OCR-D-N9 -O OCR-D-N10 >>ocrd.log 2>&1
/usr/bin/time ocrd-cis-ocropy-clip -I OCR-D-N10 -O OCR-D-N11 -P level-of-operation line >>ocrd.log 2>&1
/usr/bin/time ocrd-cis-ocropy-resegment -I OCR-D-N11 -O OCR-D-N12 >>ocrd.log 2>&1
/usr/bin/time ocrd-cis-ocropy-dewarp -I OCR-D-N12 -O OCR-D-N13 >>ocrd.log 2>&1
/usr/bin/time ocrd-calamari-recognize -I OCR-D-N13 -O OCR-D-OCR -P checkpoint "$HOME/ocrd_models/calamari/GT4HistOCR/*.ckpt.json" >>ocrd.log 2>&1
```

Image:
https://digi.ub.uni-heidelberg.de/diglitData/v/ocrd/dobbert1861_-_14.tif

 * git log of ocrd_all: commit 39a946255f8276a01b17055b300f1ddbc267187a
 * git log of ocrd_all/ocrd_cis: commit 5ec0e34026930961bbc300e70d0d2586f14b7411

```
(venv) [hd_XXX@login5 ocrd_all]$ ocrd-cis-ocropy-resegment --version
Version 0.1.5, ocrd/core 2.19.0
```

**Comment by bertsky** [comment] 2020-11-04 22:15
Thanks @jbarth-ubhd! I can reproduce. 

You exposed a bug that's been lurking there ever since. What happened was that sometimes (due to rounding), cropping can result in -1 as a bbox's left boundary. But if you feed that as a slice to a numpy array, it will be interpreted from the right, so the array will only be 1px wide/high.

This only surfaced because you were using resegmentation after clipping on the line level – which is generally not useful (as the latter can do the former in a much better way), so the images/arrays were already very tight.

I have a couple of other fixes in the line for ocrd_cis tools. I'll publish them tomorrow as part of the ever growing #77.

**Comment by jbarth-ubhd** [comment] 2020-11-05 10:24
Oops. clip(line) + resegment is not an "allowed" combination here: https://ocr-d.de/en/workflows . Must have been an copy&paste error. Sorry for opening this case.

**Comment by bertsky** [comment] 2020-11-05 10:33
> clip(line) + resegment is not an "allowed" combination here: https://ocr-d.de/en/workflows

It _is_ allowed, but not useful. (What's not allowed is clipping after another step producing derived images on the same level, e.g. line-level dewarping before line-level clipping, or region-level deskewing before region-level clipping.)

> Sorry for opening this case.

As I said above, you _did_ find an error, and as long as #77 is not merged, I'll keep this open.

**Comment by jbarth-ubhd** [comment] 2020-11-05 11:14
ok but clip(line) & resegment are listed in "Step 12: Resegmentation (Line Level)", so from the documentation I would not do both.

**Comment by bertsky** [comment] 2020-11-05 11:25
> ok but clip(line) & resegment are listed in "Step 12: Resegmentation (Line Level)", so from the documentation I would not do both.

Well, technically, you could combine them with clipping as a _fall-back_ to resegmentation: in case the latter fails on a line (because it cannot match a good, single polygonal outline to the existing bbox) the former can still achieve _something_ on the components directly crossing the margin. (But your ordering does not make sense AFAICT.)

**Closed** 2022-03-04 11:18 UTC
